### ISSUE TITLE
Sonde vs serial id

### ISSUE THREAD

**Issue by hgloeckner** [Geet-George/halodrops#127]
Currently the sonde_id variable in level 2 is set as the serial_id of the sonde (if I understand that correctly). We might have to change that to follow the campaign standard naming thingy. (didn't think it was too important; but I might forget to change that if I don't write it down)

**Comment by Geet-George** [comment]
The `sonde_id` should not have any information in its semantics, and should only be unique. Any convention (e.g. campaign standard) would likely be misinterpreted as carrying information. This is what we decided for EUREC4A, and therefore called the `sonde_id` only as a unique identifier and explicitly mentioned this in the data paper. I think the best way to keep it this way and keep a sonde unique would be to identify it with the serial number of the instrument, which would be unique. @d70-t can correct my thinking here, but this is what we had discussed back during JOANNE, right?

**Comment by hgloeckner** [comment]
Yeah that makes sense. We somehow discussed about this and somehow thought that there was another decision made somewhere. But maybe that's also wrong

**Comment by d70-t** [comment]
Just to emphasize: we've tried naming sondes "cleverly" e.g. by flight and then counting. This failed because it was not clear if launch order or initialization order is the best, and if we should count failed sondes or not etc... This resulted in renaming sondes over time, which very much defeats the idea of an identifier.
The serial number is uniquely assigned to a sonde, so there's no ambiguity, which is the most crucial feature for an identifier.

**Comment by hgloeckner** [comment]
Nice, then we just leave it with the serial id as a sonde_id
